# Generated by Django 3.2.7 on 2021-09-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainblog', '0003_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
    ]
